version: "3.8"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=azamat
      - MONGO_PASSWORD=azamat998877
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=azamat
      - MONGO_INITDB_ROOT_PASSWORD=azamat998877